# ===============================
# PostgreSql (dev/prod \uACF5\uD1B5 \uC778\uC2A4\uD134\uC2A4, \uAC12\uB9CC env\uB85C \uC8FC\uC785)
# ===============================
spring.datasource.url=jdbc:postgresql://s3.java21.net:8000/aiot3-team3-project?currentSchema=ai
spring.datasource.username=aiot3-team3
spring.datasource.password=${DB_PASSWORD}
spring.jpa.open-in-view=false
# ===============================
# InfluxDB
# ===============================
influxdb.url=http://insighton-influxdb:8086
influxdb.org=insighton
influxdb.bucket=insighton-bucket
influxdb.token=${INFLUXDB_TOKEN}
