spring.application.name=insighton-ai

management.endpoints.web.exposure.include=health,prometheus

core-service.url=http://insighton-core

# ===============================
# Spring AI - Gemini
# ===============================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash


