# prod 프로파일에서만 다른 설정. 공통 설정은 application.properties 참고.

spring.config.import=classpath:config/prod/actuator.properties, classpath:config/prod/swagger.properties, classpath:config/prod/db.properties, classpath:config/prod/zipkin.properties

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ===============================
# Redis
# ===============================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=323

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=s4.java21.net
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


